/**
 * Detects if a username looks auto-generated by the Supabase trigger.
 * Pattern: ends with _XX to _XXXXX where X is alphanumeric (e.g. "cam_bd3e", "user_a7f2").
 */
export function isAutoGeneratedUsername(username: string): boolean {
  return /_[a-z0-9]{2,5}$/.test(username);
}
