"use client";

import { useEffect, useState, useRef, useCallback } from "react";
import { useUser } from "@/app/contexts/auth";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import Image from "next/image";
import { Check, X, Loader2 } from "lucide-react";
import { isAutoGeneratedUsername } from "@/lib/onboarding";

const RESERVED = new Set([
  "admin", "api", "www", "sterp", "about", "login", "signup",
  "dashboard", "settings", "help", "support", "terms", "privacy",
  "home", "explore", "archive", "onboarding",
]);

type ValidationState =
  | { status: "idle" }
  | { status: "error"; message: string }
  | { status: "checking" }
  | { status: "available" }
  | { status: "taken" };

export default function OnboardingUsernamePage() {
  const { user, loading: authLoading } = useUser();
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [validation, setValidation] = useState<ValidationState>({ status: "idle" });
  const [submitting, setSubmitting] = useState(false);
  const [checkingProfile, setCheckingProfile] = useState(true);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Redirect unauthenticated users to login
  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
    }
  }, [authLoading, user, router]);

  // Check onboarding state and redirect accordingly
  useEffect(() => {
    if (!user) return;
    const supabase = createClient();
    supabase
      .from("users")
      .select("username, name")
      .eq("id", user.id)
      .single()
      .then(({ data }) => {
        if (!data) return;
        const hasRealUsername = !isAutoGeneratedUsername(data.username);
        if (hasRealUsername && data.name) {
          // Fully onboarded — go to dashboard
          router.replace("/dashboard");
        } else if (hasRealUsername && !data.name) {
          // Has username but no name — skip to profile step
          router.replace("/onboarding/profile");
        } else {
          // Needs username — show this page
          setCheckingProfile(false);
        }
      });
  }, [user, router]);

  const checkAvailability = useCallback(async (value: string) => {
    try {
      const res = await fetch(`/api/username/check?username=${encodeURIComponent(value)}`);
      const data = await res.json();
      // Only update if this is still the current value
      setValidation((prev) => {
        if (prev.status !== "checking") return prev;
        return data.available
          ? { status: "available" }
          : { status: "taken" };
      });
    } catch {
      setValidation({ status: "error", message: "Check failed" });
    }
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const raw = e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "");
    setUsername(raw);

    if (debounceRef.current) clearTimeout(debounceRef.current);

    if (!raw) {
      setValidation({ status: "idle" });
      return;
    }

    if (raw.length < 3) {
      setValidation({ status: "error", message: "Must be at least 3 characters" });
      return;
    }

    if (RESERVED.has(raw)) {
      setValidation({ status: "error", message: "This username is reserved" });
      return;
    }

    setValidation({ status: "checking" });
    debounceRef.current = setTimeout(() => checkAvailability(raw), 300);
  };

  const handleSubmit = async () => {
    if (validation.status !== "available" || submitting) return;

    setSubmitting(true);
    try {
      const res = await fetch("/api/username/claim", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username }),
      });

      if (res.ok) {
        router.push("/onboarding/profile");
      } else {
        const data = await res.json();
        setValidation({ status: "error", message: data.error || "Something went wrong" });
      }
    } catch {
      setValidation({ status: "error", message: "Something went wrong" });
    } finally {
      setSubmitting(false);
    }
  };

  if (authLoading || checkingProfile) {
    return (
      <div className="min-h-screen bg-[#EEF2F7] flex items-center justify-center">
        <Loader2 className="w-5 h-5 animate-spin text-neutral-400" />
      </div>
    );
  }

  const isValid = validation.status === "available";

  return (
    <div className="min-h-screen bg-[#EEF2F7] flex flex-col items-center justify-center px-4">
      <div className="w-full max-w-md flex flex-col items-center">
        {/* Logo */}
        <Image
          src="/logo-black.png"
          alt="Sterp"
          width={100}
          height={32}
          className="mb-10 h-7 w-auto"
          priority
        />

        {/* Headline */}
        <h1 className="text-2xl font-semibold text-neutral-900 mb-8 text-center">
          Claim your Sterp URL
        </h1>

        {/* Input */}
        <div className="w-full">
          <div className="flex items-center bg-white rounded-lg border border-neutral-200 focus-within:border-neutral-400 transition-colors overflow-hidden">
            <span className="pl-4 pr-1 text-[15px] text-neutral-400 select-none whitespace-nowrap">
              sterp.com/
            </span>
            <input
              type="text"
              value={username}
              onChange={handleChange}
              onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
              className="flex-1 py-3 pr-4 text-[15px] text-neutral-900 bg-transparent outline-none placeholder:text-neutral-300"
              placeholder="yourname"
              autoFocus
              autoCapitalize="off"
              autoCorrect="off"
              spellCheck={false}
            />
          </div>

          {/* Validation feedback */}
          <div className="h-6 mt-2 flex items-center gap-1.5 pl-1">
            {validation.status === "checking" && (
              <span className="flex items-center gap-1.5 text-[13px] text-neutral-400">
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                Checking...
              </span>
            )}
            {validation.status === "available" && (
              <span className="flex items-center gap-1.5 text-[13px] text-emerald-600">
                <Check className="w-3.5 h-3.5" />
                Available
              </span>
            )}
            {validation.status === "taken" && (
              <span className="flex items-center gap-1.5 text-[13px] text-red-500">
                <X className="w-3.5 h-3.5" />
                Taken
              </span>
            )}
            {validation.status === "error" && (
              <span className="flex items-center gap-1.5 text-[13px] text-red-500">
                <X className="w-3.5 h-3.5" />
                {validation.message}
              </span>
            )}
          </div>
        </div>

        {/* Continue button */}
        <button
          onClick={handleSubmit}
          disabled={!isValid || submitting}
          className="w-full mt-4 py-3 rounded-lg text-[15px] font-medium text-white transition-all disabled:opacity-40 disabled:cursor-not-allowed"
          style={{ backgroundColor: "#C0392B" }}
        >
          {submitting ? "Claiming..." : "Continue"}
        </button>
      </div>
    </div>
  );
}
