"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useUser } from "@/app/contexts/auth";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import Image from "next/image";
import { Camera, Loader2 } from "lucide-react";
import { isAutoGeneratedUsername } from "@/lib/onboarding";
import { ensureUserRow } from "@/lib/ensure-user-row";
import Cropper from "react-easy-crop";
import type { Area } from "react-easy-crop";

// ─── Image helpers (mirrored from dashboard) ───────────────────────

function isHeic(file: File): boolean {
  return (
    file.type === "image/heic" ||
    file.type === "image/heif" ||
    /\.heic$/i.test(file.name)
  );
}

async function convertHeicToJpeg(file: File): Promise<File> {
  const heic2any = (await import("heic2any")).default;
  const blob = await heic2any({ blob: file, toType: "image/jpeg", quality: 0.92 });
  const result = Array.isArray(blob) ? blob[0] : blob;
  return new File([result], file.name.replace(/\.heic$/i, ".jpg"), { type: "image/jpeg" });
}

async function convertToWebP(file: File): Promise<Blob> {
  const MAX_WIDTH = 1200;
  return new Promise((resolve, reject) => {
    const img = new globalThis.Image();
    const objectUrl = URL.createObjectURL(file);
    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      let w = img.width;
      let h = img.height;
      if (w > MAX_WIDTH) {
        h = Math.round(h * (MAX_WIDTH / w));
        w = MAX_WIDTH;
      }
      const canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext("2d");
      if (!ctx) return reject(new Error("Canvas not supported"));
      ctx.drawImage(img, 0, 0, w, h);
      canvas.toBlob(
        (blob) => (blob ? resolve(blob) : reject(new Error("Conversion failed"))),
        "image/webp",
        0.85
      );
    };
    img.onerror = () => { URL.revokeObjectURL(objectUrl); reject(new Error("Failed to load image")); };
    img.src = objectUrl;
  });
}

async function getCroppedBlob(imageSrc: string, cropArea: Area): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const img = new globalThis.Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = cropArea.width;
      canvas.height = cropArea.height;
      const ctx = canvas.getContext("2d");
      if (!ctx) return reject(new Error("Canvas not supported"));
      ctx.drawImage(
        img,
        cropArea.x, cropArea.y, cropArea.width, cropArea.height,
        0, 0, cropArea.width, cropArea.height
      );
      canvas.toBlob(
        (blob) => (blob ? resolve(blob) : reject(new Error("Crop failed"))),
        "image/jpeg",
        0.95
      );
    };
    img.onerror = () => reject(new Error("Failed to load image"));
    img.src = imageSrc;
  });
}

// ─── Crop Modal (same as dashboard) ─────────────────────────────────

function CropModal({ imageSrc, onDone, onCancel }: {
  imageSrc: string;
  onDone: (croppedBlob: Blob) => void;
  onCancel: () => void;
}) {
  const [crop, setCrop] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const [croppedArea, setCroppedArea] = useState<Area | null>(null);

  const handleCropComplete = useCallback((_: Area, croppedAreaPixels: Area) => {
    setCroppedArea(croppedAreaPixels);
  }, []);

  async function handleDone() {
    if (!croppedArea) return;
    const blob = await getCroppedBlob(imageSrc, croppedArea);
    onDone(blob);
  }

  return (
    <div role="dialog" aria-modal="true" aria-label="Crop image" className="fixed inset-0 z-[60] bg-black flex flex-col">
      <div className="relative flex-1">
        <Cropper
          image={imageSrc}
          crop={crop}
          zoom={zoom}
          aspect={1}
          onCropChange={setCrop}
          onZoomChange={setZoom}
          onCropComplete={handleCropComplete}
          showGrid={true}
        />
      </div>
      <div className="flex items-center gap-4 px-6 py-4 pb-[max(1rem,env(safe-area-inset-bottom))] bg-black">
        <input
          type="range"
          min={1}
          max={3}
          step={0.1}
          value={zoom}
          onChange={(e) => setZoom(Number(e.target.value))}
          className="flex-1 accent-white"
        />
        <button type="button" onClick={onCancel} className="text-[15px] text-white/70 hover:text-white">
          Cancel
        </button>
        <button
          type="button"
          onClick={handleDone}
          className="text-[15px] font-medium text-white bg-[#C0392B] px-6 py-2 rounded-md hover:opacity-90"
        >
          Done
        </button>
      </div>
    </div>
  );
}

// ─── Page ───────────────────────────────────────────────────────────

export default function OnboardingProfilePage() {
  const { user, loading: authLoading } = useUser();
  const router = useRouter();

  const [name, setName] = useState("");
  const [bio, setBio] = useState("");
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const [avatarBlob, setAvatarBlob] = useState<Blob | null>(null);
  const [cropSrc, setCropSrc] = useState<string | null>(null);
  const [avatarError, setAvatarError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [checkingProfile, setCheckingProfile] = useState(true);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Redirect unauthenticated users
  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
    }
  }, [authLoading, user, router]);

  // Check onboarding state and redirect accordingly
  useEffect(() => {
    if (!user) return;
    ensureUserRow(user).then(() => {
      const supabase = createClient();
      supabase
        .from("users")
        .select("username, name, bio")
        .eq("id", user.id)
        .single()
        .then(({ data }) => {
          if (!data) return;
          if (isAutoGeneratedUsername(data.username)) {
            router.replace("/onboarding/username");
            return;
          }
          // bio !== null means user already completed step 2
          if (data.name && data.bio !== null) {
            router.replace("/dashboard");
            return;
          }
          const oauthName =
            user.user_metadata?.full_name ||
            user.user_metadata?.name ||
            "";
          if (oauthName) setName(oauthName);
          setCheckingProfile(false);
        });
    });
  }, [user, router]);

  function handleFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 10 * 1024 * 1024) {
      setAvatarError("Max 10MB");
      return;
    }
    (async () => {
      try {
        const converted = isHeic(file) ? await convertHeicToJpeg(file) : file;
        if (cropSrc) URL.revokeObjectURL(cropSrc);
        setCropSrc(URL.createObjectURL(converted));
        setAvatarError(null);
      } catch {
        setAvatarError("Could not read this image format");
      }
    })();
  }

  function handleCropDone(croppedBlob: Blob) {
    if (cropSrc) URL.revokeObjectURL(cropSrc);
    setCropSrc(null);
    setAvatarBlob(croppedBlob);
    setAvatarPreview(URL.createObjectURL(croppedBlob));
    if (fileInputRef.current) fileInputRef.current.value = "";
  }

  function handleCropCancel() {
    if (cropSrc) URL.revokeObjectURL(cropSrc);
    setCropSrc(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  }

  async function handleSubmit() {
    if (!name.trim() || !user || submitting) return;

    setSubmitting(true);
    try {
      const supabase = createClient();

      // Upload avatar if provided
      let avatar_url: string | null = null;
      if (avatarBlob) {
        const file = new File([avatarBlob], "avatar.jpg", { type: "image/jpeg" });
        const webpBlob = await convertToWebP(file);
        const filePath = `${user.id}/avatar.webp`;

        const { error: uploadError } = await supabase.storage
          .from("product-photos")
          .upload(filePath, webpBlob, {
            contentType: "image/webp",
            upsert: true,
          });

        if (uploadError) throw new Error(uploadError.message);
        avatar_url = `https://images.sterp.com/${filePath}?t=${Date.now()}`;
      }

      // Save profile
      const updates: Record<string, string | null> = {
        name: name.trim(),
        bio: bio.trim(),
      };
      if (avatar_url) updates.avatar_url = avatar_url;

      const { error: updateError } = await supabase
        .from("users")
        .update(updates)
        .eq("id", user.id);

      if (updateError) throw new Error(updateError.message);

      router.push("/dashboard");
    } catch {
      setAvatarError("Something went wrong — try again");
    } finally {
      setSubmitting(false);
    }
  }

  if (authLoading || checkingProfile) {
    return (
      <div className="min-h-screen bg-[#EEF2F7] flex items-center justify-center">
        <Loader2 className="w-5 h-5 animate-spin text-neutral-400" />
      </div>
    );
  }

  const inputClass =
    "w-full rounded-md bg-white border border-gray-200 shadow-sm px-3 py-2 text-[15px] text-neutral-900 focus:outline-none focus:ring-2 focus:ring-[#C0392B]/20 focus:border-[#C0392B]/40";

  return (
    <div className="min-h-screen bg-[#EEF2F7] flex flex-col items-center justify-center px-4">
      <div className="w-full max-w-sm mx-auto flex flex-col items-center">
        {/* Logo */}
        <Image
          src="/logo-charcoal.png"
          alt="Sterp"
          width={100}
          height={32}
          className="mb-10 h-7 w-auto"
          priority
        />

        {/* Headline */}
        <h1 className="text-2xl font-semibold tracking-tight text-neutral-900 mb-8 text-center">
          Set up your profile
        </h1>

        {/* Avatar upload */}
        <div className="mb-4">
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="relative w-24 h-24 rounded-full bg-white border-2 border-dashed border-gray-300 overflow-hidden group cursor-pointer"
          >
            {avatarPreview ? (
              <img src={avatarPreview} alt="Avatar" className="w-full h-full object-cover" />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                <Camera className="w-6 h-6 text-[#C0392B]" />
              </div>
            )}
            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <Camera className="w-5 h-5 text-white" />
            </div>
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*,.heic"
            onChange={handleFileSelect}
            className="hidden"
          />
          {avatarError && (
            <p className="text-[13px] text-red-500 mt-2 text-center">{avatarError}</p>
          )}
        </div>

        {/* Name */}
        <div className="w-full mb-4">
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            className={inputClass}
            placeholder="Your name"
            autoFocus
          />
        </div>

        {/* Bio */}
        <div className="w-full mb-6">
          <div className="relative">
            <textarea
              value={bio}
              onChange={(e) => {
                if (e.target.value.length <= 160) setBio(e.target.value);
              }}
              rows={3}
              className={`${inputClass} resize-none pb-6`}
              placeholder="A short bio (optional)"
            />
            <span
              className={`absolute bottom-2 right-3 text-xs ${
                bio.length >= 140 ? "text-[#C0392B]" : "text-gray-400"
              }`}
            >
              {bio.length}/160
            </span>
          </div>
        </div>

        {/* Continue button */}
        <button
          onClick={handleSubmit}
          disabled={!name.trim() || submitting}
          className="w-full py-3 rounded-lg text-[15px] font-medium text-white bg-[#C0392B] hover:bg-red-700 transition-all disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-[#C0392B]"
        >
          {submitting ? "Saving..." : "Continue"}
        </button>
      </div>

      {/* Crop modal */}
      {cropSrc && (
        <CropModal
          imageSrc={cropSrc}
          onDone={handleCropDone}
          onCancel={handleCropCancel}
        />
      )}
    </div>
  );
}
