"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { createPortal } from "react-dom";
import { useUser } from "@/app/contexts/auth";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import Image from "next/image";
import { Clock, Camera, Flame } from "lucide-react";
import { isAutoGeneratedUsername } from "@/lib/onboarding";
import { ensureUserRow } from "@/lib/ensure-user-row";
import {
  DndContext,
  closestCenter,
  TouchSensor,
  PointerSensor,
  KeyboardSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  verticalListSortingStrategy,
  sortableKeyboardCoordinates,
  arrayMove,
} from "@dnd-kit/sortable";

import type { Product, Collection, Obsession, Profile } from "./lib/types";
import { extractHandle, handleToUrl, slugify, normalizeUrl, isHeic, convertHeicToJpeg, convertToWebP, uploadProductPhoto, inputClass } from "./lib/utils";
import { useIsTouchDevice } from "./hooks/use-is-touch-device";
import { Thumbnail } from "./components/thumbnail";
import { StatusBadge } from "./components/status-badge";
import { CropModal } from "./components/crop-modal";
import { CustomDropdown } from "./components/custom-dropdown";
import { ArchiveModal } from "./components/archive-modal";
import { DeleteModal } from "./components/delete-modal";
import { ProductModal } from "./components/product-modal";
import { DragHandle, SortableObsession, SortableCollection, SortableProduct } from "./components/sortable-wrappers";
import { DashboardHeader } from "./components/dashboard-header";
import { GreenBanners } from "./components/green-banners";
import { ArchiveSection } from "./components/archive-section";
import { EditProfileModal } from "./components/edit-profile-modal";
import { ProductRow } from "./components/product-row";
import { ObsessionsSection } from "./components/obsessions-section";
import { CollectionsSection } from "./components/collections-section";


// ─── Main component ─────────────────────────────────────────────────

export default function DashboardPage() {
  const { user, loading: authLoading } = useUser();
  const router = useRouter();

  const [products, setProducts] = useState<Product[]>([]);
  const [collections, setCollections] = useState<Collection[]>([]);
  const [obsessions, setObsessions] = useState<Obsession[]>([]);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [loading, setLoading] = useState(true);

  // Copy link feedback
  const [copied, setCopied] = useState(false);

  // Avatar upload
  const avatarInputRef = useRef<HTMLInputElement>(null);
  const [avatarUploading, setAvatarUploading] = useState(false);
  const [avatarError, setAvatarError] = useState<string | null>(null);
  const [avatarCropSrc, setAvatarCropSrc] = useState<string | null>(null);

  // Profile inline editing
  const [profileName, setProfileName] = useState("");
  const [profileBio, setProfileBio] = useState("");
  const [profileTwitter, setProfileTwitter] = useState("");
  const [profileInstagram, setProfileInstagram] = useState("");
  const [profileYoutube, setProfileYoutube] = useState("");
  const [socialOrder, setSocialOrder] = useState<("twitter" | "instagram" | "youtube")[]>(["twitter", "instagram", "youtube"]);
  const openProfileModal = () => {
    const vals: Record<string, string> = { twitter: profileTwitter, instagram: profileInstagram, youtube: profileYoutube };
    const all: ("twitter" | "instagram" | "youtube")[] = ["twitter", "instagram", "youtube"];
    setSocialOrder([...all.filter(k => vals[k].trim()), ...all.filter(k => !vals[k].trim())]);
    setProfileModalOpen(true);
  };

  // Product modal
  const [productModal, setProductModal] = useState<{
    mode: "add" | "edit";
    collectionId?: string;
    product?: Product;
  } | null>(null);

  // Scroll-to + highlight after adding a product
  const [highlightProductId, setHighlightProductId] = useState<string | null>(null);

  // Add collection
  const [showAddCollection, setShowAddCollection] = useState(false);
  const [newCollectionName, setNewCollectionName] = useState("");
  const [addCollectionError, setAddCollectionError] = useState("");

  // Rename collection
  const [renamingCollectionId, setRenamingCollectionId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState("");
  const [renameError, setRenameError] = useState("");

  // Collection errors (for delete)
  const [collectionError, setCollectionError] = useState("");

  // Post-live nudge (one-time, localStorage)
  const [nudgeDismissed, setNudgeDismissed] = useState<boolean | null>(null);
  useEffect(() => {
    setNudgeDismissed(localStorage.getItem("sterp_nudge_dismissed") === "true");
  }, []);
  function dismissNudge() {
    localStorage.setItem("sterp_nudge_dismissed", "true");
    setNudgeDismissed(true);
  }

  // Product overflow menu
  const [productMenuOpen, setProductMenuOpen] = useState<string | null>(null);

  // Archive & delete modals
  const [archiveTarget, setArchiveTarget] = useState<Product | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; name: string; type: "product" | "collection" | "archived" } | null>(null);

  // ─── Data fetching ──────────────────────────────────────────────

  const fetchProducts = useCallback(async () => {
    const res = await fetch("/api/products");
    if (res.ok) setProducts(await res.json());
  }, []);

  const fetchCollections = useCallback(async () => {
    const res = await fetch("/api/collections");
    if (res.ok) setCollections(await res.json());
  }, []);

  const fetchObsessions = useCallback(async () => {
    const res = await fetch("/api/obsessions");
    if (res.ok) setObsessions(await res.json());
  }, []);

  const fetchProfile = useCallback(async () => {
    if (!user) return;
    await ensureUserRow(user);
    const supabase = createClient();
    const { data } = await supabase
      .from("users")
      .select("username, name, bio, avatar_url, twitter_url, instagram_url, youtube_url")
      .eq("id", user.id)
      .single();
    if (data) {
      // Onboarding interception
      if (isAutoGeneratedUsername(data.username)) {
        router.replace("/onboarding/username");
        return;
      }
      // bio === null means user hasn't completed profile setup (step 2).
      // After step 2, bio is set to "" (empty string) if left blank.
      if (!data.name || data.bio === null) {
        router.replace("/onboarding/profile");
        return;
      }
      setProfile(data);
      setProfileName(data.name || "");
      setProfileBio(data.bio || "");
      setProfileTwitter(extractHandle(data.twitter_url || "", "twitter"));
      setProfileInstagram(extractHandle(data.instagram_url || "", "instagram"));
      setProfileYoutube(extractHandle(data.youtube_url || "", "youtube"));
    }
  }, [user, router]);

  const fetchAll = useCallback(async () => {
    setLoading(true);
    await Promise.all([fetchProducts(), fetchCollections(), fetchObsessions(), fetchProfile()]);
    setLoading(false);
  }, [fetchProducts, fetchCollections, fetchObsessions, fetchProfile]);

  // Auth redirect
  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
    }
  }, [authLoading, user, router]);

  // Initial data load
  useEffect(() => {
    if (user) fetchAll();
  }, [user, fetchAll]);

  // ─── Profile actions ─────────────────────────────────────────────

  const [profileSaved, setProfileSaved] = useState(false);
  const [profileModalOpen, setProfileModalOpen] = useState(false);

  async function saveProfileField(field: string, value: string) {
    if (!user || !profile) return;
    let normalized: string;
    if (field === "twitter_url") normalized = handleToUrl(value, "twitter");
    else if (field === "instagram_url") normalized = handleToUrl(value, "instagram");
    else if (field === "youtube_url") normalized = handleToUrl(value, "youtube");
    else if (field.endsWith("_url")) normalized = normalizeUrl(value);
    else normalized = value.trim();
    const current = (profile as unknown as Record<string, unknown>)[field] ?? "";
    if ((normalized || "") === (current || "")) return;
    const supabase = createClient();
    const { error } = await supabase
      .from("users")
      .update({ [field]: normalized || null })
      .eq("id", user.id);
    if (!error) {
      setProfile((prev) => prev ? { ...prev, [field]: normalized || null } : prev);
      setProfileSaved(true);
      setTimeout(() => setProfileSaved(false), 2000);
    }
  }

  async function saveAllProfileFields() {
    if (!user) return;
    const supabase = createClient();
    const { error } = await supabase
      .from("users")
      .update({
        name: profileName.trim() || null,
        bio: profileBio.trim() || null,
        twitter_url: handleToUrl(profileTwitter, "twitter") || null,
        instagram_url: handleToUrl(profileInstagram, "instagram") || null,
        youtube_url: handleToUrl(profileYoutube, "youtube") || null,
      })
      .eq("id", user.id);
    if (!error) {
      setProfileSaved(true);
      setTimeout(() => setProfileSaved(false), 2000);
    }
  }

  async function handleAvatarFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file || !user) return;
    if (file.size > 10 * 1024 * 1024) { setAvatarError("Max 10MB"); return; }
    try {
      const converted = isHeic(file) ? await convertHeicToJpeg(file) : file;
      if (avatarCropSrc) URL.revokeObjectURL(avatarCropSrc);
      setAvatarCropSrc(URL.createObjectURL(converted));
      setAvatarError(null);
    } catch {
      setAvatarError("Could not read this image format");
    }
  }

  async function handleAvatarCropDone(croppedBlob: Blob) {
    setAvatarCropSrc(null);
    if (!user) return;
    setAvatarUploading(true);
    setAvatarError(null);
    try {
      const file = new File([croppedBlob], "avatar.jpg", { type: "image/jpeg" });
      const webpBlob = await convertToWebP(file);
      const supabase = createClient();
      const filePath = `${user.id}/avatar.webp`;

      const { error: uploadError } = await supabase.storage
        .from("product-photos")
        .upload(filePath, webpBlob, {
          contentType: "image/webp",
          upsert: true,
        });

      if (uploadError) throw new Error(uploadError.message);

      const avatar_url = `https://images.sterp.com/${filePath}?t=${Date.now()}`;

      const { error: updateError } = await supabase
        .from("users")
        .update({ avatar_url })
        .eq("id", user.id);

      if (updateError) throw new Error(updateError.message);

      setProfile((prev) => prev ? { ...prev, avatar_url } : prev);
    } catch {
      setAvatarError("Avatar upload failed — try again");
    } finally {
      setAvatarUploading(false);
      if (avatarInputRef.current) avatarInputRef.current.value = "";
    }
  }

  async function handleCopyLink() {
    if (!profile?.username) return;
    try {
      await navigator.clipboard.writeText(`https://sterp.com/${profile.username}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API unavailable (e.g. HTTP or unsupported browser)
    }
  }

  // ─── Product actions ────────────────────────────────────────────

  async function handleArchiveConfirm(note: string | null, archivedAt: string, acquiredAt: string | null) {
    if (!archiveTarget) return;
    const res = await fetch(`/api/products/${archiveTarget.id}/archive`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ archive_note: note, archived_at: archivedAt, acquired_at: acquiredAt }),
    });
    if (res.ok) {
      await Promise.all([fetchProducts(), fetchObsessions()]);
    }
    setArchiveTarget(null);
  }

  async function handleDeleteConfirm() {
    if (!deleteTarget) return;
    if (deleteTarget.type === "collection") {
      setCollectionError("");
      const res = await fetch(`/api/collections/${deleteTarget.id}`, { method: "DELETE" });
      if (!res.ok) {
        const data = await res.json();
        setCollectionError(data.error || "Failed to delete collection");
      } else {
        await fetchCollections();
      }
    } else {
      const res = await fetch(`/api/products/${deleteTarget.id}`, { method: "DELETE" });
      if (res.ok) {
        await Promise.all([fetchProducts(), fetchObsessions()]);
      }
    }
    setDeleteTarget(null);
  }

  // ─── Obsessions actions ─────────────────────────────────────────

  const [showAddObsession, setShowAddObsession] = useState(false);
  const [obsessionSearch, setObsessionSearch] = useState("");
  const [obsessionFilter, setObsessionFilter] = useState("");

  async function handleRemoveObsession(productId: string) {
    const res = await fetch(`/api/obsessions/${productId}`, { method: "DELETE" });
    if (res.ok) await fetchObsessions();
  }

  async function handleAddObsession(productId: string) {
    const res = await fetch("/api/obsessions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ product_id: productId }),
    });
    if (res.ok) {
      await fetchObsessions();
      setShowAddObsession(false);
      setObsessionSearch("");
      setObsessionFilter("");
    }
  }

  async function handleReorderObsessions(fromIdx: number, toIdx: number) {
    const sorted = [...obsessions].sort((a, b) => a.sort_order - b.sort_order);
    const reordered = arrayMove(sorted, fromIdx, toIdx).map((tp, i) => ({ ...tp, sort_order: i + 1 }));
    setObsessions(reordered);
    const res = await fetch("/api/obsessions/reorder", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ order: reordered.map((tp) => tp.product_id) }),
    });
    if (!res.ok) await fetchObsessions();
  }

  // ─── Collection + Product drag state ────────────────────────────

  const [collapsedCollections, setCollapsedCollections] = useState<Set<string>>(new Set());
  const [collectionMenuOpen, setCollectionMenuOpen] = useState<string | null>(null);

  function toggleCollapsed(id: string) {
    setCollapsedCollections((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function handleReorderCollections(fromIdx: number, toIdx: number) {
    const sorted = [...collections].sort((a, b) => a.sort_order - b.sort_order);
    const reordered = arrayMove(sorted, fromIdx, toIdx).map((c, i) => ({ ...c, sort_order: i }));
    setCollections(reordered);
    const res = await fetch("/api/collections/reorder", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ order: reordered.map((c) => c.id) }),
    });
    if (!res.ok) await fetchCollections();
  }

  async function handleReorderProducts(collectionId: string, fromIdx: number, toIdx: number) {
    const colProducts = products
      .filter((p) => p.collection_id === collectionId && p.status === "current")
      .sort((a, b) => a.sort_order - b.sort_order);
    const reordered = arrayMove(colProducts, fromIdx, toIdx);
    const updatedIds = new Set(reordered.map((p) => p.id));
    const newProducts = products.map((p) => {
      if (!updatedIds.has(p.id)) return p;
      return { ...p, sort_order: reordered.findIndex((cp) => cp.id === p.id) };
    });
    setProducts(newProducts);
    const res = await fetch("/api/products/reorder", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ collection_id: collectionId, order: reordered.map((p) => p.id) }),
    });
    if (!res.ok) await fetchProducts();
  }

  // ─── dnd-kit sensors & handlers ─────────────────────────────────

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
    useSensor(TouchSensor, { activationConstraint: { delay: 200, tolerance: 5 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  );

  function handleObsessionDragEnd(event: DragEndEvent) {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const sorted = [...obsessions].sort((a, b) => a.sort_order - b.sort_order);
    const oldIndex = sorted.findIndex((tp) => tp.product_id === active.id);
    const newIndex = sorted.findIndex((tp) => tp.product_id === over.id);
    if (oldIndex !== -1 && newIndex !== -1) {
      handleReorderObsessions(oldIndex, newIndex);
    }
  }

  function handleCollectionDragEnd(event: DragEndEvent) {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const sorted = [...collections].sort((a, b) => a.sort_order - b.sort_order);
    const oldIndex = sorted.findIndex((c) => c.id === active.id);
    const newIndex = sorted.findIndex((c) => c.id === over.id);
    if (oldIndex !== -1 && newIndex !== -1) {
      handleReorderCollections(oldIndex, newIndex);
    }
  }

  function handleProductDragEnd(collectionId: string) {
    return (event: DragEndEvent) => {
      const { active, over } = event;
      if (!over || active.id === over.id) return;
      const colProducts = products
        .filter((p) => p.collection_id === collectionId && p.status === "current")
        .sort((a, b) => a.sort_order - b.sort_order);
      const oldIndex = colProducts.findIndex((p) => p.id === active.id);
      const newIndex = colProducts.findIndex((p) => p.id === over.id);
      if (oldIndex !== -1 && newIndex !== -1) {
        handleReorderProducts(collectionId, oldIndex, newIndex);
      }
    };
  }

  // ─── Collection actions ─────────────────────────────────────────

  async function handleAddCollection(e: React.FormEvent) {
    e.preventDefault();
    setAddCollectionError("");
    if (!newCollectionName.trim()) {
      setAddCollectionError("Name is required");
      return;
    }
    const res = await fetch("/api/collections", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newCollectionName.trim() }),
    });
    if (!res.ok) {
      const data = await res.json();
      setAddCollectionError(data.error || "Failed to add collection");
      return;
    }
    setNewCollectionName("");
    setShowAddCollection(false);
    await fetchCollections();
  }

  async function handleRenameCollection(id: string) {
    setRenameError("");
    if (!renameValue.trim()) {
      setRenameError("Name is required");
      return;
    }
    const res = await fetch(`/api/collections/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: renameValue.trim() }),
    });
    if (!res.ok) {
      const data = await res.json();
      setRenameError(data.error || "Failed to rename");
      return;
    }
    setRenamingCollectionId(null);
    await fetchCollections();
  }

  // handleDeleteCollection replaced by deleteTarget modal flow

  // ─── Archive actions ───────────────────────────────────────────

  const [editingNoteId, setEditingNoteId] = useState<string | null>(null);
  const [editNoteValue, setEditNoteValue] = useState("");
  const [editAcquiredMonth, setEditAcquiredMonth] = useState("");
  const [editAcquiredYear, setEditAcquiredYear] = useState("");
  const [editArchivedMonth, setEditArchivedMonth] = useState("");
  const [editArchivedYear, setEditArchivedYear] = useState("");

  function openArchiveEdit(p: Product) {
    setEditingNoteId(p.id);
    setEditNoteValue(p.archive_note || "");
    const acq = p.acquired_at ? new Date(p.acquired_at) : p.created_at ? new Date(p.created_at) : null;
    setEditAcquiredMonth(acq ? String(acq.getUTCMonth() + 1) : "");
    setEditAcquiredYear(acq ? String(acq.getUTCFullYear()) : "");
    const arch = p.archived_at ? new Date(p.archived_at) : null;
    setEditArchivedMonth(arch ? String(arch.getUTCMonth() + 1) : "");
    setEditArchivedYear(arch ? String(arch.getUTCFullYear()) : "");
  }

  async function handleSaveArchiveNote(id: string) {
    const res = await fetch(`/api/products/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        archive_note: editNoteValue.trim() || null,
        acquired_at: editAcquiredMonth && editAcquiredYear ? `${editAcquiredYear}-${editAcquiredMonth.padStart(2, "0")}-01` : null,
        archived_at: editArchivedMonth && editArchivedYear ? `${editArchivedYear}-${editArchivedMonth.padStart(2, "0")}-01T00:00:00Z` : null,
      }),
    });
    if (res.ok) {
      setEditingNoteId(null);
      await fetchProducts();
    }
  }

  async function handleRestoreProduct(id: string) {
    const res = await fetch(`/api/products/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: "current" }),
    });
    if (res.ok) {
      await fetchProducts();
    }
  }

  function formatDuration(createdAt: string, archivedAt: string): string {
    const start = new Date(createdAt);
    const end = new Date(archivedAt);
    const totalMonths = (end.getFullYear() - start.getFullYear()) * 12 + (end.getMonth() - start.getMonth());
    if (totalMonths < 1) return "Owned for < 1 month";
    if (totalMonths < 12) return `Owned for ${totalMonths} month${totalMonths === 1 ? "" : "s"}`;
    const years = totalMonths / 12;
    const cleanHalf = totalMonths % 6 === 0;
    if (cleanHalf && totalMonths % 12 !== 0) return `Owned for ${years} years`;
    const wholeYears = Math.round(years);
    return `Owned for ${wholeYears} year${wholeYears === 1 ? "" : "s"}`;
  }

  // ─── Lookups ────────────────────────────────────────────────────

  const collectionMap = new Map(collections.map((c) => [c.id, c]));
  const currentProducts = products.filter((p) => p.status === "current");
  const productCount = currentProducts.length;
  const hasNamedCollection = collections.some((c) => c.name !== "Products");
  const phase = productCount < 5 ? 1 : productCount === 5 ? 2 : hasNamedCollection ? 4 : 3;
  const [liveBannerDismissed, setLiveBannerDismissed] = useState<boolean | null>(null);
  useEffect(() => {
    setLiveBannerDismissed(localStorage.getItem("sterp_live_banner_dismissed") === "true");
  }, []);
  const archivedProducts = products
    .filter((p) => p.status === "archived")
    .sort((a, b) => {
      const aDate = a.archived_at ? new Date(a.archived_at).getTime() : 0;
      const bDate = b.archived_at ? new Date(b.archived_at).getTime() : 0;
      return bDate - aDate;
    });

  // Count products per collection
  const productCountByCollection = new Map<string, number>();
  for (const p of products.filter((p) => p.status === "current" || p.status === "draft")) {
    const count = productCountByCollection.get(p.collection_id) || 0;
    productCountByCollection.set(p.collection_id, count + 1);
  }

  // ─── Loading / auth guard ──────────────────────────────────────

  if (authLoading || !user) {
    return (
      <div className="min-h-screen bg-[#EEF2F7]">
        <div className="mx-auto max-w-2xl px-4 pt-6 sm:pt-10 pb-4 animate-pulse">
          <div className="flex items-center justify-between">
            <div className="h-[50px] w-[150px] bg-neutral-200/60 rounded" />
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-full bg-neutral-200/60" />
              <div className="space-y-1.5">
                <div className="h-3.5 w-24 bg-neutral-200/60 rounded" />
                <div className="h-2.5 w-32 bg-neutral-100 rounded" />
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ─── Render ─────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-[#EEF2F7]">
      <DashboardHeader
        profile={profile}
        currentProducts={currentProducts}
        copied={copied}
        onEditProfile={openProfileModal}
        onCopyLink={handleCopyLink}
        onLogout={async () => { await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); }}
      />

      <div className="mx-auto max-w-2xl px-4 pb-16">
        {loading ? (
          <div className="space-y-6 animate-pulse">
            {/* Add Product button skeleton */}
            <div className="flex justify-center">
              <div className="w-[60%] h-[48px] bg-neutral-200/60 rounded-lg" />
            </div>
            {/* Product rows skeleton */}
            {[...Array(5)].map((_, i) => (
              <div key={i} className="flex items-center gap-3 bg-white rounded-lg px-4 py-3 border border-gray-200">
                <div className="h-10 w-10 rounded bg-neutral-200/80 flex-shrink-0" />
                <div className="flex-1 space-y-2">
                  <div className="h-4 w-2/5 bg-neutral-200/80 rounded" />
                  <div className="h-3 w-3/5 bg-neutral-100 rounded" />
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="space-y-6">
            {profile?.username && (
              <GreenBanners
                username={profile.username}
                currentProducts={currentProducts}
                productCount={productCount}
                phase={phase}
                copied={copied}
                nudgeDismissed={nudgeDismissed}
                liveBannerDismissed={liveBannerDismissed}
                onCopyLink={handleCopyLink}
                onDismissLiveBanner={() => { localStorage.setItem("sterp_live_banner_dismissed", "true"); setLiveBannerDismissed(true); }}
                onDismissNudge={dismissNudge}
                onCreateCollection={() => { setShowAddCollection(true); setAddCollectionError(""); }}
              />
            )}

            {/* ─── First-run composition (zero products) ── */}
            {products.length === 0 && (
              <div className="text-center pt-10 pb-4">
                <h2 className="text-[22px] font-semibold text-neutral-800 mb-2">
                  What are you obsessed with right now?
                </h2>
                <p className="text-[15px] text-neutral-400 mb-6">
                  The stuff you can&apos;t stop talking about. Add 3 to make your page live.
                </p>
                <button
                  onClick={() => setProductModal({ mode: "add" })}
                  className="w-[45%] text-white text-[15px] font-semibold py-3 rounded-lg hover:opacity-90 transition-opacity"
                  style={{ backgroundColor: "#C0392B" }}
                >
                  + Add Product
                </button>
              </div>
            )}

            {/* ─── Persistent Add Product button ── */}
            {products.length > 0 && (
              <div className="text-center">
                <button
                  onClick={() => setProductModal({ mode: "add" })}
                  className="w-[60%] text-white text-[15px] font-semibold py-3 rounded-lg hover:opacity-90 transition-opacity"
                  style={{ backgroundColor: "#C0392B" }}
                >
                  + Add Product
                </button>
              </div>
            )}

            {/* ─── Add Collection form (triggered from green banner CTA in Phase 3) ── */}
            {products.length > 0 && phase === 3 && showAddCollection && (
              <form
                onSubmit={handleAddCollection}
                className="bg-white rounded-lg border border-gray-200 p-4 flex items-end gap-3"
              >
                <div className="flex-1">
                  <label className="block text-[13px] font-medium text-neutral-600 mb-1">
                    Collection name
                  </label>
                  <input
                    type="text"
                    value={newCollectionName}
                    onChange={(e) => setNewCollectionName(e.target.value)}
                    className={inputClass}
                    placeholder="e.g. Home Office, Gym Setup"
                  />
                  {addCollectionError && (
                    <p className="text-[13px] text-[#C0392B] mt-1">{addCollectionError}</p>
                  )}
                </div>
                <button
                  type="submit"
                  className="bg-[#C0392B] text-white text-[14px] font-medium px-4 py-2 rounded-md hover:opacity-90 transition-opacity flex-shrink-0"
                >
                  Add
                </button>
              </form>
            )}

            {/* ─── Phase 1: Flat product list (building Obsessions) ── */}
            {products.length > 0 && phase === 1 && (
              <section>
                <div className="space-y-2">
                  {products
                    .filter((p) => p.status === "current" || p.status === "draft")
                    .sort((a, b) => a.sort_order - b.sort_order)
                    .map((p) => (
                      <ProductRow
                        key={p.id}
                        product={p}
                        highlighted={highlightProductId === p.id}
                        menuOpen={productMenuOpen === p.id}
                        onToggleMenu={() => setProductMenuOpen(productMenuOpen === p.id ? null : p.id)}
                        onCloseMenu={() => setProductMenuOpen(null)}
                        onEdit={() => setProductModal({ mode: "edit", product: p })}
                        onArchive={() => setArchiveTarget(p)}
                        className="bg-white rounded-lg px-4 py-3 border border-gray-200"
                      />
                    ))}
                </div>
              </section>
            )}

            {/* ─── Section 3: Obsessions (Phase 2+) ──────────────────────── */}
            {products.length > 0 && phase >= 2 && (
              <ObsessionsSection
                products={products}
                collections={collections}
                obsessions={obsessions}
                currentProducts={currentProducts}
                phase={phase}
                highlightProductId={highlightProductId}
                productMenuOpen={productMenuOpen}
                showAddObsession={showAddObsession}
                obsessionSearch={obsessionSearch}
                obsessionFilter={obsessionFilter}
                sensors={sensors}
                collectionMap={collectionMap}
                onSetProductMenuOpen={setProductMenuOpen}
                onSetShowAddObsession={setShowAddObsession}
                onSetObsessionSearch={setObsessionSearch}
                onSetObsessionFilter={setObsessionFilter}
                onEditProduct={(p) => setProductModal({ mode: "edit", product: p })}
                onRemoveObsession={handleRemoveObsession}
                onAddObsession={handleAddObsession}
                onObsessionDragEnd={handleObsessionDragEnd}
              />
            )}

            {/* ─── Phase 3: Flat list for non-obsession products ── */}
            {products.length > 0 && phase === 3 && (() => {
              const obsessionIds = new Set(obsessions.map((tp) => tp.product_id));
              const nonObsessionProducts = products
                .filter((p) => (p.status === "current" || p.status === "draft") && !obsessionIds.has(p.id))
                .sort((a, b) => a.sort_order - b.sort_order);
              if (nonObsessionProducts.length === 0) return null;
              return (
                <section>
                  <div className="space-y-2">
                    {nonObsessionProducts.map((p) => (
                      <ProductRow
                        key={p.id}
                        product={p}
                        highlighted={highlightProductId === p.id}
                        menuOpen={productMenuOpen === p.id}
                        onToggleMenu={() => setProductMenuOpen(productMenuOpen === p.id ? null : p.id)}
                        onCloseMenu={() => setProductMenuOpen(null)}
                        onEdit={() => setProductModal({ mode: "edit", product: p })}
                        onArchive={() => setArchiveTarget(p)}
                        className="bg-white rounded-lg px-4 py-3 border border-gray-200"
                      />
                    ))}
                  </div>
                </section>
              );
            })()}

            {/* ─── Section 4: Collections (Phase 4+) ── */}
            {products.length > 0 && phase >= 4 && (
              <CollectionsSection
                products={products}
                collections={collections}
                profile={profile}
                highlightProductId={highlightProductId}
                productMenuOpen={productMenuOpen}
                showAddCollection={showAddCollection}
                newCollectionName={newCollectionName}
                addCollectionError={addCollectionError}
                collectionError={collectionError}
                renamingCollectionId={renamingCollectionId}
                renameValue={renameValue}
                renameError={renameError}
                collapsedCollections={collapsedCollections}
                collectionMenuOpen={collectionMenuOpen}
                productCountByCollection={productCountByCollection}
                sensors={sensors}
                onSetProductMenuOpen={setProductMenuOpen}
                onSetShowAddCollection={setShowAddCollection}
                onSetNewCollectionName={setNewCollectionName}
                onSetAddCollectionError={setAddCollectionError}
                onSetRenamingCollectionId={setRenamingCollectionId}
                onSetRenameValue={setRenameValue}
                onSetRenameError={setRenameError}
                onSetCollectionMenuOpen={setCollectionMenuOpen}
                onToggleCollapsed={toggleCollapsed}
                onAddCollection={handleAddCollection}
                onRenameCollection={handleRenameCollection}
                onDeleteCollection={(c) => setDeleteTarget({ id: c.id, name: c.name, type: "collection" })}
                onEditProduct={(p) => setProductModal({ mode: "edit", product: p })}
                onArchiveProduct={(p) => setArchiveTarget(p)}
                onAddProduct={(collectionId) => setProductModal({ mode: "add", collectionId })}
                onCollectionDragEnd={handleCollectionDragEnd}
                onProductDragEnd={handleProductDragEnd}
                slugify={slugify}
              />
            )}

            <ArchiveSection
              archivedProducts={archivedProducts}
              editingNoteId={editingNoteId}
              editNoteValue={editNoteValue}
              setEditNoteValue={setEditNoteValue}
              editAcquiredMonth={editAcquiredMonth}
              setEditAcquiredMonth={setEditAcquiredMonth}
              editAcquiredYear={editAcquiredYear}
              setEditAcquiredYear={setEditAcquiredYear}
              editArchivedMonth={editArchivedMonth}
              setEditArchivedMonth={setEditArchivedMonth}
              editArchivedYear={editArchivedYear}
              setEditArchivedYear={setEditArchivedYear}
              onOpenEdit={openArchiveEdit}
              onSaveNote={handleSaveArchiveNote}
              onRestore={handleRestoreProduct}
              onDelete={(p) => setDeleteTarget({ id: p.id, name: p.name, type: "archived" })}
              onCancelEdit={() => setEditingNoteId(null)}
              formatDuration={formatDuration}
            />
            {/* All nudges now live in the Green Banner System at the top */}
          </div>
        )}
      </div>

      {/* Product Modal */}
      {productModal && (
        <ProductModal
          mode={productModal.mode}
          product={productModal.product}
          defaultCollectionId={productModal.collectionId}
          collections={collections}
          obsessions={obsessions}
          userId={user.id}
          phase={phase}
          onSave={async (newProductId?: string) => {
            await Promise.all([fetchProducts(), fetchCollections(), fetchObsessions()]);
            if (newProductId) {
              setHighlightProductId(newProductId);
              setTimeout(() => {
                document.querySelector(`[data-product-id="${newProductId}"]`)?.scrollIntoView({ behavior: "smooth", block: "center" });
              }, 100);
              setTimeout(() => setHighlightProductId(null), 2500);
            }
          }}
          onClose={() => setProductModal(null)}
          onCollectionCreated={fetchCollections}
          onArchive={(p) => { setProductModal(null); setArchiveTarget(p); }}
          onDelete={(p) => { setProductModal(null); setDeleteTarget({ id: p.id, name: p.name, type: "product" }); }}
        />
      )}

      {/* Avatar Crop Modal */}
      {avatarCropSrc && (
        <CropModal
          imageSrc={avatarCropSrc}
          aspect={1}
          onDone={handleAvatarCropDone}
          onCancel={() => { if (avatarCropSrc) URL.revokeObjectURL(avatarCropSrc); setAvatarCropSrc(null); if (avatarInputRef.current) avatarInputRef.current.value = ""; }}
        />
      )}
      {archiveTarget && (
        <ArchiveModal
          product={archiveTarget}
          onConfirm={handleArchiveConfirm}
          onCancel={() => setArchiveTarget(null)}
        />
      )}
      {deleteTarget && (
        <DeleteModal
          name={deleteTarget.name}
          onConfirm={handleDeleteConfirm}
          onCancel={() => setDeleteTarget(null)}
        />
      )}

      {/* Edit Profile Modal */}
      {profileModalOpen && profile && (
        <EditProfileModal
          profile={profile}
          profileName={profileName}
          setProfileName={setProfileName}
          profileBio={profileBio}
          setProfileBio={setProfileBio}
          profileTwitter={profileTwitter}
          setProfileTwitter={setProfileTwitter}
          profileInstagram={profileInstagram}
          setProfileInstagram={setProfileInstagram}
          profileYoutube={profileYoutube}
          setProfileYoutube={setProfileYoutube}
          socialOrder={socialOrder}
          avatarUploading={avatarUploading}
          avatarError={avatarError}
          avatarInputRef={avatarInputRef}
          profileSaved={profileSaved}
          onAvatarFileSelect={handleAvatarFileSelect}
          onSaveField={saveProfileField}
          onSaveAll={saveAllProfileFields}
          onClose={() => setProfileModalOpen(false)}
        />
      )}
    </div>
  );
}
